# Generated by Django 3.2.25 on 2024-03-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexe', models.CharField(choices=[('male', 'Homme'), ('female', 'Femme')], max_length=6, verbose_name='Sexe')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('date_naissance', models.DateField(verbose_name='Date de Naissance')),
                ('lieu_naissance', models.CharField(max_length=100, verbose_name='Lieu de Naissance')),
                ('situation_familiale', models.CharField(choices=[('single', 'Célibataire'), ('married', 'Marié(e)'), ('divorced', 'Divorcé(e)'), ('widowed', 'Veuf/Veuve')], max_length=10, verbose_name='Situation Familiale')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('mobile', models.CharField(max_length=20, verbose_name='Mobile')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('diplome', models.CharField(blank=True, choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD'), ('other', 'Autre')], max_length=10, null=True, verbose_name='Diplôme')),
                ('specialite', models.CharField(max_length=100, verbose_name='Spécialité')),
            ],
        ),
    ]
