# Generated by Django 3.2.25 on 2024-04-02 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrjob',
            name='active',
        ),
        migrations.RemoveField(
            model_name='hrjob',
            name='department',
        ),
        migrations.RemoveField(
            model_name='hrjob',
            name='description',
        ),
        migrations.RemoveField(
            model_name='hrjob',
            name='requirements',
        ),
    ]
