# Generated by Django 3.2.25 on 2024-03-28 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='candidat',
        ),
    ]
