# Generated by Django 3.2.25 on 2024-04-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0002_auto_20240402_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruitment_id', models.CharField(max_length=100, unique=True, verbose_name='Recrutement')),
                ('intitule', models.CharField(max_length=100, verbose_name='Intitulé du poste')),
                ('descr', models.TextField(verbose_name='Description du poste')),
                ('niveau', models.CharField(choices=[('bac', 'Baccalauréat'), ('licence', 'Licence'), ('master', 'Master'), ('doctorat', 'Doctorat')], max_length=20, verbose_name="Niveau d'étude")),
                ('diplome', models.CharField(choices=[('g', 'f')], max_length=1, verbose_name='Diplôme')),
                ('formation', models.CharField(choices=[('g', 'f')], max_length=1, verbose_name='Formation')),
                ('formation_experience', models.CharField(choices=[('g', 'f')], max_length=1, verbose_name="Formation liée à l'expérience du poste")),
                ('savoir_faire', models.TextField(verbose_name='Savoir-faire')),
                ('savoir_etre', models.TextField(verbose_name='Savoir-être')),
                ('type', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD')], default='CDI', max_length=3, verbose_name='Type de contrat')),
                ('horaires', models.CharField(blank=True, max_length=100, null=True, verbose_name='Horaires de travail')),
                ('remuneration', models.FloatField(default=0, verbose_name='Rémunération')),
            ],
            options={
                'verbose_name': 'Description',
                'verbose_name_plural': 'Descriptions',
                'db_table': 'sirh_desc',
            },
        ),
    ]
