# Generated by Django 3.2.25 on 2024-04-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0002_alter_employee_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approche', models.CharField(max_length=255, verbose_name='Approche')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('descriptif_societe', models.TextField(verbose_name='Descriptif de la société')),
                ('description_poste', models.TextField(verbose_name='Description du poste')),
                ('profil_recherche', models.TextField(verbose_name='Profil recherché')),
                ('modalite_reponse', models.TextField(verbose_name='Modalité de réponse')),
            ],
            options={
                'db_table': 'annonce',
            },
        ),
        migrations.CreateModel(
            name='Desc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(blank=True, max_length=100, null=True, verbose_name='Intitulé du poste')),
                ('descr', models.TextField(blank=True, null=True, verbose_name='Description du poste')),
                ('niveau', models.CharField(blank=True, max_length=10, null=True, verbose_name="Niveau d'étude")),
                ('diplome', models.CharField(blank=True, max_length=1, null=True, verbose_name='Diplôme')),
                ('formation', models.CharField(blank=True, max_length=1, null=True, verbose_name='Formation')),
                ('formation_experience', models.CharField(blank=True, max_length=1, null=True, verbose_name="Formation liée à l'expérience du poste")),
                ('savoir_faire', models.TextField(blank=True, null=True, verbose_name='Savoir-faire')),
                ('savoir_etre', models.TextField(blank=True, null=True, verbose_name='Savoir-être')),
                ('type', models.CharField(blank=True, max_length=3, null=True, verbose_name='Type de contrat')),
                ('horaires', models.CharField(blank=True, max_length=100, null=True, verbose_name='Horaires de travail')),
                ('remuneration', models.FloatField(blank=True, null=True, verbose_name='Rémunération')),
                ('recruitment_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de recrutement')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(blank=True, choices=[('interne', 'Recrutement interne'), ('temp', 'Remplacement temporaire'), ('retr', 'Retraite')], max_length=10, null=True, verbose_name='Motif de recrutement')),
                ('pourex', models.IntegerField(blank=True, null=True, verbose_name="Pour l'exercice")),
                ('budget', models.FloatField(blank=True, null=True, verbose_name='Budget')),
                ('intitule', models.CharField(blank=True, max_length=100, null=True, verbose_name='Intitulé du poste')),
                ('echeance_contrat', models.DateField(blank=True, null=True, verbose_name='Échéance du contrat')),
                ('xp', models.IntegerField(blank=True, null=True, verbose_name="Années d'expérience")),
                ('lieu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lieu de travail')),
                ('deplacement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Déplacement à prévoir')),
                ('autre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Autres aspects à considérer')),
                ('date_entree', models.DateField(blank=True, null=True, verbose_name="Date d'entrée")),
                ('annonce_id', models.CharField(blank=True, max_length=100, null=True, verbose_name="ID de l'annonce")),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='diplome',
        ),
        migrations.AddField(
            model_name='employee',
            name='diplome_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID du Diplôme'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='adresse',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de Naissance'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lieu de Naissance'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='situation_familiale',
            field=models.CharField(blank=True, choices=[('single', 'Célibataire'), ('married', 'Marié(e)'), ('divorced', 'Divorcé(e)'), ('widowed', 'Veuf/Veuve')], max_length=10, null=True, verbose_name='Situation Familiale'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='specialite',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Spécialité'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
    ]
