# Generated by Django 3.2.25 on 2024-04-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0003_auto_20240402_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='annonce_id',
            new_name='recruitment_id',
        ),
        migrations.AddField(
            model_name='annonce',
            name='recruitment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="ID de l'annonce"),
        ),
    ]
