# Generated by Django 3.2.25 on 2024-04-03 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0003_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='description_id',
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='recruitment_id',
        ),
        migrations.RemoveField(
            model_name='description',
            name='recruitment_id',
        ),
    ]
