# Generated by Django 3.2.25 on 2024-04-03 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0004_auto_20240403_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recrutement',
            old_name='description_id',
            new_name='desc_id',
        ),
    ]
