# Generated by Django 3.2.25 on 2024-04-02 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0004_auto_20240402_0926'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='desc',
            table='rh_desc',
        ),
        migrations.AlterModelTable(
            name='form',
            table='rh_form',
        ),
    ]
