# Generated by Django 3.2.25 on 2024-05-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0005_rename_description_id_recrutement_desc_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='approche',
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='contenu',
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='descriptif_societe',
        ),
        migrations.AddField(
            model_name='annonce',
            name='accroche',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='activity_date_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='create_uid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='desc_poste',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='desc_societe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='message_last_post',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='write_uid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='modalite_reponse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='obligations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='profil_recherche',
            field=models.TextField(blank=True, null=True),
        ),
    ]
