# Generated by Django 3.2.25 on 2024-05-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0006_auto_20240528_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Besoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(blank=True, max_length=255, null=True)),
                ('pourex', models.IntegerField(blank=True, null=True)),
                ('budget', models.FloatField(blank=True, null=True)),
                ('intitule', models.IntegerField(blank=True, null=True)),
                ('echeanceContrat', models.DateField(blank=True, null=True)),
                ('xp', models.IntegerField(blank=True, null=True)),
                ('lieu', models.CharField(blank=True, max_length=255, null=True)),
                ('deplacement', models.CharField(blank=True, max_length=255, null=True)),
                ('autre', models.CharField(blank=True, max_length=255, null=True)),
                ('dateEntree', models.DateField(blank=True, null=True)),
                ('domaine_ex', models.CharField(blank=True, max_length=255, null=True)),
                ('desc_id', models.IntegerField(blank=True, null=True)),
                ('annonce_id', models.IntegerField(blank=True, null=True)),
                ('create_uid', models.IntegerField(blank=True, null=True)),
                ('write_uid', models.IntegerField(blank=True, null=True)),
                ('activity_date_deadline', models.DateField(blank=True, null=True)),
                ('message_last_post', models.DateTimeField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('write_date', models.DateTimeField(blank=True, null=True)),
                ('descr', models.TextField(blank=True, null=True)),
                ('niveau', models.IntegerField(blank=True, null=True)),
                ('diplome', models.TextField(blank=True, null=True)),
                ('formation', models.TextField(blank=True, null=True)),
                ('formation_oblig', models.TextField(blank=True, null=True)),
                ('savoir_faire', models.TextField(blank=True, null=True)),
                ('savoir_etre', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('horaires', models.IntegerField(blank=True, null=True)),
                ('remuneration', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sirh_besoin',
            },
        ),
        migrations.DeleteModel(
            name='Description',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='HRJob',
        ),
        migrations.DeleteModel(
            name='Recrutement',
        ),
        migrations.AlterField(
            model_name='annonce',
            name='accroche',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='activity_date_deadline',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='create_uid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='desc_poste',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='desc_societe',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='message_last_post',
            field=models.DateTimeField(default='2000-01-01 00:00:00'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='modalite_reponse',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='obligations',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='profil_recherche',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='write_uid',
            field=models.IntegerField(default=0),
        ),
    ]
