# Generated by Django 3.2.25 on 2024-05-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0007_auto_20240528_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('expected_employees', models.IntegerField()),
                ('no_of_employee', models.IntegerField()),
                ('no_of_recruitment', models.IntegerField()),
                ('no_of_hired_employee', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('department_id', models.IntegerField()),
                ('company_id', models.IntegerField()),
                ('state', models.CharField(max_length=255)),
                ('message_last_post', models.DateTimeField(blank=True, null=True)),
                ('create_uid', models.IntegerField()),
                ('create_date', models.DateTimeField()),
                ('write_uid', models.IntegerField()),
                ('write_date', models.DateTimeField()),
                ('address_id', models.IntegerField()),
                ('manager_id', models.IntegerField()),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('hr_responsible_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hr_job',
            },
        ),
    ]
