# Generated by Django 3.2.25 on 2024-05-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0008_hrjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('datas_fname', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('res_name', models.CharField(max_length=255)),
                ('res_model', models.CharField(max_length=255)),
                ('res_field', models.CharField(max_length=255)),
                ('res_id', models.IntegerField()),
                ('create_date', models.DateTimeField()),
                ('company_id', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=1024)),
                ('public', models.BooleanField()),
                ('access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('db_datas', models.BinaryField(blank=True, null=True)),
                ('store_fname', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('checksum', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=255)),
                ('index_content', models.TextField(blank=True, null=True)),
                ('write_uid', models.IntegerField()),
                ('write_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'ir_attachment',
            },
        ),
        migrations.AlterField(
            model_name='hrjob',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
