# Generated by Django 3.2.25 on 2024-05-31 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0011_auto_20240530_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrapplicant',
            name='stage_id',
            field=models.IntegerField(blank=True, default='1', null=True),
        ),
    ]
