# Generated by Django 3.2.25 on 2024-05-31 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0013_alter_hrapplicant_stage_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='besoin',
            name='annonce_id',
        ),
        migrations.RemoveField(
            model_name='besoin',
            name='dateEntree',
        ),
        migrations.RemoveField(
            model_name='besoin',
            name='desc_id',
        ),
        migrations.RemoveField(
            model_name='besoin',
            name='echeanceContrat',
        ),
        migrations.AddField(
            model_name='annonce',
            name='besoin_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annonce',
            name='create_date',
            field=models.DateTimeField(default='2024-05-31 12:00:00'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='write_date',
            field=models.DateTimeField(default='2024-05-31 12:00:00'),
        ),
        migrations.AddField(
            model_name='besoin',
            name='date_entree',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='besoin',
            name='echeance_contrat',
            field=models.DateField(default='2024-12-31'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='accroche',
            field=models.CharField(default='Accroche par défaut', max_length=255),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='activity_date_deadline',
            field=models.DateField(default='2024-06-30'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='desc_poste',
            field=models.TextField(default='Description du poste par défaut'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='desc_societe',
            field=models.TextField(default='Description de la société par défaut'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='message_last_post',
            field=models.DateTimeField(default='2024-05-31 12:00:00'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='modalite_reponse',
            field=models.CharField(default='Modalités de réponse par défaut', max_length=255),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='obligations',
            field=models.TextField(default='Obligations par défaut'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='profil_recherche',
            field=models.TextField(default='Profil recherché par défaut'),
        ),
        migrations.AlterField(
            model_name='besoin',
            name='activity_date_deadline',
            field=models.DateField(default='2024-06-30'),
        ),
        migrations.AlterField(
            model_name='besoin',
            name='autre',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='besoin',
            name='budget',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='besoin',
            name='create_date',
            field=models.DateTimeField(default='2024-05-31 12:00:00'),
        ),
        migrations.AlterField(
            model_name='besoin',
            name='create_uid',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='besoin',
            name='deplacement',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='besoin',
            name='descr',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='besoin',
            name='diplome',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='besoin',
            name='domaine_ex',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='besoin',
            name='formation',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='besoin',
            name='formation_oblig',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='besoin',
            name='horaires',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='besoin',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='besoin',
            name='intitule',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='besoin',
            name='lieu',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='besoin',
            name='message_last_post',
            field=models.DateTimeField(default='2024-05-31 12:00:00'),
        ),
        migrations.AlterField(
            model_name='besoin',
            name='motif',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='besoin',
            name='niveau',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='besoin',
            name='pourex',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='besoin',
            name='remuneration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='besoin',
            name='savoir_etre',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='besoin',
            name='savoir_faire',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='besoin',
            name='type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='besoin',
            name='write_date',
            field=models.DateTimeField(default='2024-05-31 12:00:00'),
        ),
        migrations.AlterField(
            model_name='besoin',
            name='write_uid',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='besoin',
            name='xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='activity_date_deadline',
            field=models.DateField(blank=True, default='2024-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='availability',
            field=models.DateField(blank=True, default='2024-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='campaign_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='color',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='company_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='create_date',
            field=models.DateTimeField(default='2024-01-01 00:00:00'),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='create_uid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='date_closed',
            field=models.DateTimeField(blank=True, default='2024-01-01 00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='date_last_stage_update',
            field=models.DateTimeField(blank=True, default='2024-01-01 00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='date_naissance',
            field=models.DateField(default='2024-01-01', verbose_name='Date de Naissance'),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='date_open',
            field=models.DateTimeField(blank=True, default='2024-01-01 00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='datedepot',
            field=models.DateField(default='2024-01-01', verbose_name='Date dépôt'),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='delay_close',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='department_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='email_cc',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='email_from',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='emp_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='job_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='last_stage_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='medium_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='message_last_post',
            field=models.DateTimeField(blank=True, default='2024-01-01 00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='name',
            field=models.CharField(default='Nom par défaut', max_length=255),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='partner_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='partner_mobile',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='partner_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='partner_phone',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='priority',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='probability',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='salary_expected',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='salary_expected_extra',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='salary_proposed',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='salary_proposed_extra',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='source_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='stage_id',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='type_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='user_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='write_date',
            field=models.DateTimeField(default='2024-01-01 00:00:00'),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='write_uid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
