# Generated by Django 3.2.25 on 2024-05-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0014_auto_20240531_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sequence', models.IntegerField()),
                ('create_uid', models.IntegerField()),
                ('create_date', models.DateTimeField()),
                ('write_uid', models.IntegerField()),
                ('write_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'hr_recruitment_degree',
                'ordering': ['sequence'],
            },
        ),
        migrations.RenameField(
            model_name='besoin',
            old_name='date_entree',
            new_name='dateEntree',
        ),
        migrations.RenameField(
            model_name='besoin',
            old_name='echeance_contrat',
            new_name='echeanceContrat',
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='campaign_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='color',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='company_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='create_uid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='delay_close',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='department_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='emp_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='job_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='last_stage_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='medium_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='partner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='probability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='salary_expected',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='salary_proposed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='source_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='stage_id',
            field=models.IntegerField(blank=True, default='1', null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='type_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrapplicant',
            name='write_uid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrjob',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
